### ISSUE TITLE
Copy-DockerImage Function name is incorrect

### ISSUE THREAD

**Issue by stealur** [nicholasdille/PowerShell-RegistryDocker#2]
Copy-DockerImage.ps1 contains Get-DockerImage function instead of Copy-DockerImage. Copy-DockerImage is therefore not successfully exported.

**Comment by nicholasdille** [comment]
Thanks for reporting this. Looks like a copy/paste mistake.

**Comment by nicholasdille** [comment]
Release automation is broken

**Comment by nicholasdille** [comment]
New version published https://github.com/nicholasdille/PowerShell-RegistryDocker/releases/tag/0.7.7.14
